# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GH_TOKEN: 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
  NPM_TOKEN: 056ca857-2ec1-4eeb-90e1-7f5ab377306a

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/feature/npm-semantic-release-1

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: feature-toggle-client
    type: javascript
    to: semantic-release
    npmCmds:
    - 'npm install'
    - 'npm run test'
    - 'npm run build'
