# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GH_TOKEN: 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
  #NPM_TOKEN: d93c450b-fe47-4f5e-96ee-2c38d672c8bb
  NPM_TOKEN: fb09d2a5-4dd4-49f7-91a1-66839bb1bf07

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/feature/npm-semantic-release-1

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: feature-toggle-client
    type: javascript
    to: semantic-release
    npmCmds:
    - 'npm install'
    - 'npm run test'
    - 'npm run build'
